version: 2
enable-beta-ecosystems: true # required for the pub package manager
updates:
  - package-ecosystem: "pub"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gradle"
    directory: "/android/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gradle"
    directory: "/android/flutter_plugins/qrscanner_zxing/android/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/helper/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "zxing-cpp"
