name: qrscanner_mlkit_example
description: Demonstrates how to use the qrscanner_mlkit plugin.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=2.17.0-266.1.beta <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  qrscanner_mlkit:
    path: ../

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true