name: Android

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.0.5'
      - run: |
          flutter config
          flutter --version

      - uses: actions/checkout@v2
        with:
          path: 'app'

      - name: Check app versions
        run: |
          python set-version.py
          git diff --exit-code
        working-directory: ./app

      - name: Run flutter tests
        run: |
          flutter test
          flutter analyze
        working-directory: ./app

      - name: Generate Third party licenses
        run: ./gradlew collectLicenses
        working-directory: ./app/android

      - name: Build the App
        run: flutter build apk --release --split-per-abi && flutter build apk --release
        env:
          YUBIOATH_STORE_BASE64: ${{ secrets.YUBIOATH_STORE_BASE64 }}
          YUBIOATH_KEY_ALIAS: ${{ secrets.YUBIOATH_KEY_ALIAS }}
          YUBIOATH_KEY_PASSWORD: ${{ secrets.YUBIOATH_KEY_PASSWORD }}
          YUBIOATH_STORE_PASSWORD: ${{ secrets.YUBIOATH_STORE_PASSWORD }}
        working-directory: ./app

      - name: Check generated files
        run: git diff --exit-code
        working-directory: ./app

      - name: Run android tests
        run: |
          ./gradlew test
        working-directory: ./app/android

      - name: Upload artifacts
        run: |
          export REF=$(echo ${GITHUB_REF} | cut -d '/' -f 3,4,5,6,7 | sed -r 's/\//_/g')
          export FLUTTER_APK=build/app/outputs/flutter-apk
          export NATIVE_LIBS=build/app/intermediates/merged_native_libs/release/out/lib

          mkdir artifacts
          mv "${FLUTTER_APK}/app-arm64-v8a-release.apk"   artifacts/yubico-authenticator-arm64-v8a-${REF}.apk
          mv "${FLUTTER_APK}/app-armeabi-v7a-release.apk" artifacts/yubico-authenticator-armeabi-v7a-${REF}.apk
          mv "${FLUTTER_APK}/app-x86_64-release.apk"      artifacts/yubico-authenticator-x86_64-${REF}.apk
          mv "${FLUTTER_APK}/app-release.apk"             artifacts/yubico-authenticator-${REF}.apk

          mv build/app/outputs/mapping/release/mapping.txt artifacts/

          pushd ${NATIVE_LIBS}
          zip -r sym-arm64-v8a.zip arm64-v8a/*so
          zip -r sym-armeabi-v7a.zip armeabi-v7a/*so
          zip -r sym-x86_64.zip x86_64/*so
          popd
          mv "${NATIVE_LIBS}/*zip" artifacts/
        working-directory: ./app

      - uses: actions/upload-artifact@v2
        with:
          name: yubico-authenticator-android
          path: app/artifacts/*
