name: Linux

on: [push, pull_request]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-latest]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Check app versions
      run: |
        python set-version.py
        git diff --exit-code

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -qq swig libpcsclite-dev clang cmake ninja-build pkg-config libgtk-3-dev
        python -m pip install --upgrade pip
        pip install poetry

    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        flutter-version: '3.3.6'
    - run: flutter config --enable-linux-desktop
    - run: flutter --version

    - name: Run tests
      run: |
        flutter test
        flutter analyze

    - name: Build the Helper
      run: ./build-helper.sh

    - name: Build the app
      run: flutter build linux

    - name: Check generated files
      run: git diff --exit-code

    - name: Rename and archive app
      run: |
        export REF=$(echo ${GITHUB_REF} | cut -d '/' -f 3)
        mkdir deploy
        tar -czf deploy/yubioath-desktop-${REF}-linux-${{matrix.os}}.tar.gz -C build/linux/x64/release/bundle .

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: yubioath-desktop-linux
        path: deploy
