name: Windows

on: [push, pull_request]

jobs:
  build:

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          choco install swig
          python -m pip install --upgrade pip
          pip install poetry

      - uses: subosito/flutter-action@v1
        with:
          channel: 'beta'
      - run: flutter config --enable-windows-desktop
      - run: flutter --version

      - name: Run tests
        run: flutter test

      - name: Install ykman
        run: .\build-ykman.bat

      - name: Build the app
        run: flutter build windows

      - name: Rename and archive app bundle
        run: |
          $arr = $env:GITHUB_REF -split '/'
          $branch = $arr[2]
          $dest = "deploy\yubioath-desktop-$branch-windows"
          mkdir $dest
          mv build\windows\runner\Release\* $dest\

      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: yubioath-desktop-windows
          path: deploy
